### ISSUE TITLE
DX11 support?

### ISSUE THREAD

**Issue by kazerniel** [Friendly0Fire/GW2Radial#213]
Now that GW2's DX11 implementation is impending, I'm wondering if the mod will be updated to work with it?

**Comment by Friendly0Fire** [comment]
Yes, but not when the beta launches.

**Comment by har1mau** [comment]
Thanks. this is my fave and absolute must have addon to enjoy GW2. looking forward to DX11 support

**Comment by unrelentingsarcasm** [comment]
With the transition to DX11, will it be possible to use a different .dll naming convention to keep Arc from having to chainload radial?  ReShade seems to work as dxgi.dll without arc installed, so it seems like DX11 has a larger set it loads instead of just d3d11.

**Comment by Friendly0Fire** [comment]
The DX11 version of GW2Radial is likely to permanently move away from chainloading in favor of the addon loader.

**Comment by deafmute1** [comment]
The issue with the loader is that the project is quite dead, and if any breakages arise with dx11 or new updates they might not get fixed (for example, d3d9.dll is  now d3d11.dll and in the root folder instead of bin64/). As much as I like the ease of use of the loader (easy updates), unless you or someone else is willing to take over maintenance of it, its not going to work out.

**Comment by Friendly0Fire** [comment]
The loader is definitely not dead, it just isn't something that needs frequent updates. It's being updated to d3d11 as we speak.

**Comment by kazerniel** [comment]
> The issue with the loader is that the project is quite dead, and if any breakages arise with dx11 or new updates they might not get fixed (for example, d3d9.dll is now d3d11.dll and in the root folder instead of bin64/). As much as I like the ease of use of the loader (easy updates), unless you or someone else is willing to take over maintenance of it, its not going to work out.

Draeggiar's fork seems to be actively developed: https://github.com/Draeggiar/GW2-Addon-Manager

**Comment by Jademalo** [comment]
> Draeggiar's fork seems to be actively developed: https://github.com/Draeggiar/GW2-Addon-Manager

This isn't the loader, this is just the addon manager application.

https://github.com/gw2-addon-loader/loader-core
This is the actual loader, and is in active development with commits working towards DX11 support literally an hour ago.

https://github.com/gw2-addon-loader/GW2-Addon-Manager/tree/redesign
The addon manager is also being actively worked on on a different branch

**Comment by kazerniel** [comment]
> This isn't the loader, this is just the addon manager application.

oops, my bad

**Comment by TinyBabyOwl** [comment]
Hi. Just wondering what the status is. Is this depending on the addon loader updating to support DX11? Waiting for the DX11 feature in game to leave beta status? No rush just wondering. Really appreciate all the hard work you all put in to this free mod!

**Comment by Friendly0Fire** [comment]
The first D3D11 nightly is available [here](https://github.com/Friendly0Fire/GW2Radial/suites/5453221088/artifacts/173362844).

**Comment by Jademalo** [comment]
> What should the .dll be renamed to to test it? 

Try using the loader, that's what the name is formatted for. 
https://github.com/gw2-addon-loader/loader-core

**Comment by jnxldr** [comment]
1. Copied the gw2addon_gw2radial.dll to \Guild Wars 2\addons\gw2radial\
2. Copied latest release from https://github.com/gw2-addon-loader/loader-core to \Guild Wars 2\
3. Deleted existing gw2radial folder from \My Documents\Guild Wars 2\addons\ (just to check if that mattered)
4. --> Game launches but gw2radial isn't loaded

**gw2al_log.txt**
> [INFO] core | Addon loader v1.0 (v1.1 r33) initialized
> [INFO] core | Loading addons from "./addons" path
> [INFO] core | Loading gw2radial
> [WARN] core | Addon "gw2radial" is not loaded due to missing dependency "d3d9_wrapper"
> [ERR] core | addons/gw2radial/gw2addon_gw2radial.dll dependency missing
> [INFO] core | Done loading addons
> [INFO] core | Unloading core addon
> [INFO] core | Unloaded

**gw2radial.log**
> [12:30:57.5206505|INF] This is GW2Radial nightly-79/merge (770ad74612afd20f14de7de11867c157b16abc21)

**Comment by Jademalo** [comment]
@jnxldr https://github.com/gw2-addon-loader/d3d9_wrapper
That's a separate addon that you need, I think the addon manager installs it automatically

**Comment by jnxldr** [comment]
> @jnxldr https://github.com/gw2-addon-loader/d3d9_wrapper That's a separate addon that you need, I think the addon manager installs it automatically

Ah ha. I'm not using the addon manager (yet; probs should start). I manually copied this d3d0_wrapper release into \addons\ and now gw2radial loads, and is available in game as expected.

Thank you @Friendly0Fire and @Jademalo

**Comment by InsaniusMax** [comment]
I can report the same, already working in game, thank you both. After some testing, I can report some flickering on the pictures in the radial menu when scrolling through them and some scaling resolution issues that are not present in the main release, but I assume this has already been noticed.

**Comment by jnxldr** [comment]
> I can report the same, already working in game, thank you both. After some testing, I can report some flickering on the pictures in the radial menu when scrolling through them and some scaling resolution issues that are not present in the main release, but I assume this has already been noticed.

+1 for the report of pictures issues.

**Comment by Jademalo** [comment]
Been playing with it for a bit, functionality wise it seems to be super solid!
I've not had any major issues yet, it's been working absolutely perfectly. Was just a drop in replacement too, didn't have to modify anything.

The only thing I've noticed is a couple of small graphical issues that are different to the DX9 version. They don't seem big enough to bother making a new ticket about (especially with it being a wip and all), so I'll put them here;

![image](https://user-images.githubusercontent.com/386846/155843736-c86bd926-6ab0-4088-bede-1e6addcef4a6.png)
The drop shadows for the icons don't seem to be working correctly, and are solid black instead of transparent. There also seems to be a lot of aliasing around the icons, my assumption there is the downscaling algo isn't working so they're just being point downscaled. This isn't an issue with the preview circle, just the main radial menu.

![image](https://user-images.githubusercontent.com/386846/155843669-9c292e99-9e7c-4ed4-b862-416de368ca1a.png)
Speaking of the preview circle, it will always show the icon in Skyscale pink, rather than in the colour of the respective mount.

**Comment by Jademalo** [comment]
Hahaha nice, it's very wiggly!
...almost too wiggly, the preview circle thing now wiggles if you move the mouse too, lol. Colours are fixed though! awesome work.

**Comment by Friendly0Fire** [comment]
Please see this release for a probably-very-close-to-final build: https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.2.0-pre1
