### ISSUE TITLE
Option to disable dismount using popup keybind

### ISSUE THREAD

**Issue by kamssiopeia** [Friendly0Fire/GW2Radial#239]
**Is your feature request related to a problem? Please describe.**
I use `tab` to display mount overlay (with 200ms delay) and i still use same keybind to target. When i click tab while riding mount it dismounts me, but i want to be able to target while on mount

**Describe the solution you'd like**
Add option to disable dismounting while clicking overlay keybind

**Describe alternatives you've considered**
Add option to propagate pop-up delay value to be used to dismount. What i mean is you would need to hold  keybind the same amount of time to dismount as is needed to show popup

**Additional context**
nothing

**Comment by kamssiopeia** [comment]
I just noticed that i'm not able to target with tab anymore and in previous version that i used both things worked. I was:
* Able to target with TAB
* Popup was displayed while hodling tab for 200ms
* Clicking tab didn't dismount

**Comment by MiryksV** [comment]
> 
> 
> I just noticed that i'm unable to target with `tab` anymore and in previous version that i used both things worked.
> 
>     * I was able to target with `tab`
> 
>     * Popup was displayed while holding tab for 200ms
> 
>     * Clicking `tab` didn't dismount

Since the https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.1.0, "The Mounts radial menu will not be shown if you are mounted, its keybinds will simply dismount you immediately.", feature that you didn't get in prior version 2.1.0 where you should re-select a mount in order to dismount and permit you to re-use your key for an other action.
Have kinda same issue (https://github.com/Friendly0Fire/GW2Radial/issues/234), by using the same key to display Radial and to _Stow/Draw Weapons_ in WvW only with the Smart War™ feature.

**Comment by Friendly0Fire** [comment]
Both suggestions in @kamssiopeia's OP are now implemented.

**Comment by MiryksV** [comment]
Thanks!!

**Comment by WolfSabian** [comment]
Yes Ty \o/

**Comment by kamssiopeia** [comment]
thank you!
