### ISSUE TITLE
xinput issue windows 7

### ISSUE THREAD

**Issue by Jellodaddy** [Friendly0Fire/GW2Radial#261]
Trying to use the new GW2Radial and it refuses to work because of something to do with xinput1_4.dll.

**To Reproduce**
1. Install GW2Radial using GW2 Addon Manager
2. in System32, copy + paste xinput1_3.dll and rename the copy to xinput1_4.dll
3. Open the game and select a character
4. Game crashes and shows shader compilation error

**Expected behavior**
both GW2 and GW2Radial don't crash and let me use the addon ingame

**Screenshots**
When xinput1_4 is not present
![Capture2](https://user-images.githubusercontent.com/16126645/144767621-19cb9fd1-6bd2-40f2-bd8b-8a98966d58bf.PNG)

When xinput1_4 is present:
![Capture](https://user-images.githubusercontent.com/16126645/144767639-cbb0ee63-736d-4b6d-94f7-97590cfd4382.PNG)

**System configuration (please fill in):**
 - OS: Windows 7
 - GPU: GTX 1050ti

**Additional context**
Doesn't work with manual install either
Works fine with xinput1_4 present but only on character select screen
Tried downloading xinput1_4 from internet instead of copying 1_3 but that didn't work either

**Comment by Par0dy0faPr0** [comment]
I'm also using Windows 7 and I can confirm that I get the same error.

Manually installing the GW2Radial yields the same exact error as shown in the first screenshot (When xinput1_4 is not present) when starting the game. I am using arcdps, so I chainload GW2Radial. However, the same also happens if I remove arcdps and try to run GW2Radial solo.
The game starts after clicking ok. Then, both the game and arcdps work fine. However,  GW2Radial and its overlay do not work at all.

OS: Windows 7
GPU: GTX 1080Ti

**Comment by Friendly0Fire** [comment]
This is likely just a missing D3D dependency because Windows 7 is now unsupported. Try placing the DLL attached to this comment (unzip it first) in bin64 or the root GW2 folder or next to the addon DLL (which works might vary, so try them until one of them does)
[d3dcompiler_47.zip](https://github.com/Friendly0Fire/GW2Radial/files/7664501/d3dcompiler_47.zip)
.

**Comment by Par0dy0faPr0** [comment]
I tried with the d3dcompiler_47.DLL you attached to your comment. It did not work for both manual (d3d9_chainload due to arcdps) and GW2 Addon Manager installation. 

I tried the following combinations by putting the unzipped DLL in the following folder:
/Guild Wars 2: same error message as before (XINPUT1_4), game starts w/o GW2Radial working
/Guild Wars 2/bin64: same as above
/Guild Wars 2/addons/gw2radial: same as above
/Guild Wars 2/addons/d3d9_wrapper: same as above
/Guild Wars 2 + /Guild Wars 2/bin64: same as above
/Guild Wars 2/bin64 + /Guild Wars 2/addons/gw2radial: same as above
/Guild Wars 2 + /Guild Wars 2/addons/gw2radial: same as above
/Guild Wars 2 + /Guild Wars 2/bin64 + /Guild Wars 2/addons/gw2radial: same as above

I then tried it w/o arcdps and got the same results.

**Comment by Friendly0Fire** [comment]
This needs to be done *with* the xinput DLL also added, obviously. This is to fix the shader compilation error, it won't magically work around the xinput dependency.

**Comment by Par0dy0faPr0** [comment]
Thanks for the reminder. The Xinput4_1.DLL was in bin64 for all the tests above.

I know tried the combinations again. Putting Xinput4_1.DLL into the root of GW2 and the d3dcompiler_47.DLL into bin64, the error message disappears and the game launches. However, GW2Radial seems not to work as Alt+Shift+M does not open anything. Again, same result for both manual and Addon Manager installation.

I don't know if it could be because of the Xinput I'm using. I think it was just something I downloaded from the internet (see attachment).
[XInput1_4.zip](https://github.com/Friendly0Fire/GW2Radial/files/7671087/XInput1_4.zip)
4

**Comment by Friendly0Fire** [comment]
If the error messages disappear and reappear if you remove either of these, then the addon most likely launched successfully, but there might be something else going on still. Look for a `gw2radial.log`, `.dmp` files, or an addon loader log.

**Comment by Par0dy0faPr0** [comment]
When I start the game, a gw2al_log.txt is generated in the root directory. I tested it with installation via Addon Manger with arcdps loaded. It contains the following:
[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loaded arcdps v1.0 r406
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loading gw2radial
[ERR] core | addons/gw2radial/gw2addon_gw2radial.dll not found
[INFO] core | Loading logs
[ERR] core | addons/logs/gw2addon_logs.dll not found
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system d3d9
[INFO] core | Unloading core addon
[INFO] core | Unloaded

gw2addon_gw2radial.dll is actually present under addons/gw2radial/ . I guess that there is an issue with it getting found?..
However, no logs for GW2Radial are created in addons/logs/ . I assume that they would be created if gw2addon_gw2radial.dll would have been found and executed?

**Comment by Friendly0Fire** [comment]
That is correct. The log should be in the root folder (not addons/logs), but you'd have noticed if it was there. Since you haven't mentioned dump files either, I suspect the addon isn't getting loaded at all, so it doesn't have a chance to install its own debugging system.

This is likely some kind of incompatibility with Windows 7, but it's hard for me to diagnose. If you're feeling adventurous, [Dependency Walker](https://www.dependencywalker.com/) would be a good first step to determine whether the addon's trying to load missing dependencies.

**Comment by Friendly0Fire** [comment]
The final fix for this issue is a combination of an upcoming update to remove the XInput dependency entirely and to install Windows Update KB4019990 to fix the missing `d3dcompiler_47.dll` correctly. If further issues remain, please open a new issue.
