### ISSUE TITLE
mount queue instead of dismounting

### ISSUE THREAD

**Issue by Zathalyn** [Friendly0Fire/GW2Radial#338]
**Describe the bug**
active combat bugs out dismounting in WvW with the current pre 8 build

**To Reproduce**
1. mount up on Warclaw in WvW
2. go and get yourself into combat somewhere
3. click the assigned dismount key to try dismount and it will start the mount queue instead of dismounting you

**Expected behavior**
supposed to dismount you, mount queue should only appear when you try mount while in combat

**Comment by Zyian** [comment]
You need to set the the Dismount keybind in both the game and in Radial otherwise it will use the mount key causing the queuing. This is mentioned in the help tooltip under the Dismount keybind for Dismount

<img width="851" alt="image" src="https://user-images.githubusercontent.com/5796109/209446000-2d98f24a-c6be-47bb-b360-7b178a947f4b.png">
