### ISSUE TITLE
GW2 fails to open after install (Steamdeck)

### ISSUE THREAD

**Issue by Rakhim23** [Friendly0Fire/GW2Radial#354]
Installed the GW2 Addon manager and attempted to install GW2 Radial addon. Provider portal opens fine to input credentials for Arenanet. Fatal error occurs when launching the game "Fatal error : shader compilation failed! Error code was 0x80004005. Please report to https://github/Frienly0Fire/GW2Radial/issues"

**Comment by Zyian** [comment]
Please take a moment to read the README on the repository, it has instructions on Linux support

**Comment by Rakhim23** [comment]
> Please take a moment to read the README on the repository, it has instructions on Linux support

Thanks for the help. I used protontricks recommended and still receive the same error. Any other ideas?

**Comment by adammillerio** [comment]
I am also seeing the same crash on Steam Deck. I'll add some more info here to hopefully help out with troubleshooting:

GW2 installed via steam, launch options:
![Screenshot_20231214_132835](https://github.com/Friendly0Fire/GW2Radial/assets/2807024/c7a5c41a-119a-45a7-9ef8-f3d5a1814c21)

`-provider Portal` used because I have a non-steam GW2 account.

GW2 Path: `/home/deck/.local/share/Steam/steamapps/common/Guild Wars 2`

Contents of GW2 directory:

```
.
./Gw2-64.tmp
./dxgi.dll
./gw2al_log.txt
./addonLoader.dll
./Gw2.dat
./installscript.vdf
./THIRDPARTYSOFTWAREREADME.txt
./d3d11.dll
./Gw2-64.exe
./debug.log
./bin64
./bin64/d3dcompiler_43.dll
./bin64/dxgi.dll
./bin64/libEGL.dll
./bin64/libGLESv2.dll
./bin64/ffmpegsumo.dll
./bin64/cef
./bin64/cef/vk_swiftshader.dll
./bin64/cef/snapshot_blob.bin
./bin64/cef/dxgi.dll
./bin64/cef/icudtl.dat
./bin64/cef/en-US.pak
./bin64/cef/d3dcompiler_47.dll
./bin64/cef/chrome_100_percent.pak
./bin64/cef/libEGL.dll
./bin64/cef/libGLESv2.dll
./bin64/cef/resources.pak
./bin64/cef/vk_swiftshader_icd.json
./bin64/cef/v8_context_snapshot.bin
./bin64/cef/chrome_elf.dll
./bin64/cef/vulkan-1.dll
./bin64/cef/addons
./bin64/cef/addons/gw2radial
./bin64/cef/CefHost.exe
./bin64/cef/chrome_200_percent.pak
./bin64/cef/libcef.zip
./bin64/cef/libcef.dll
./bin64/icudt.dll
./bin64/CoherentUI_Host.exe
./bin64/CoherentUI64.dll
./addons
./addons/gw2radial
./addons/gw2radial/gw2addon_gw2radial.dll
./addons/gw2radial/config.ini
./addons/gw2radial/custom
./addons/gw2radial/custom/Menus
./addons/gw2radial/custom/Menus/config.ini
./addons/gw2radial/readme.md
./addons/d3d9_wrapper
./addons/d3d9_wrapper/gw2addon_d3d9_wrapper.pdb
./addons/d3d9_wrapper/gw2addon_d3d9_wrapper.lib
./addons/d3d9_wrapper/gw2addon_d3d9_wrapper.exp
./addons/d3d9_wrapper/gw2addon_d3d9_wrapper.dll
./gw2radial.log
```

gw2-addon-loader/loader-core manually installed

gw2-addon-loader/d3d9_wrapper manually installed

Friendly0Fire/GW2Radial manually installed

Crash after hitting “Play” in launcher:
![crash](https://github.com/Friendly0Fire/GW2Radial/assets/2807024/2fbe10fe-a22a-4952-81b5-5d84f5ffd021)

## Things tried:

### Attempt 1:

Changed launch options:

`WINEDLLOVERRIDES="d3dcompiler_43=n,b;d3dcompiler_47=n,b;d3d11_43=n,b" -provider Portal`

### Attempt 2

Installed protontricks via Discover and launched it:

Selected GW2:
![Screenshot_20231214_132450](https://github.com/Friendly0Fire/GW2Radial/assets/2807024/350e373c-132f-480f-a3ab-cfa5d2776c43)

Chose "Select the default wineprefix":

![Screenshot_20231214_132528](https://github.com/Friendly0Fire/GW2Radial/assets/2807024/deb3460f-42ca-41fa-a8ba-2f25149681a2)

Install a Windows DLL or Component:

![Screenshot_20231214_132543](https://github.com/Friendly0Fire/GW2Radial/assets/2807024/7f1c7762-048e-4f8f-846b-f6d853c49f8e)

Selected the DLLs as explained in the README for Linux:

![Screenshot_20231214_132625](https://github.com/Friendly0Fire/GW2Radial/assets/2807024/c879e18b-3f48-462c-b438-23d48b480ffd)

### Attempt 3

Same as 2, but instead selected "Run Winecfg" and added the 3 DLL overrides in the Libraries tab:

![Screenshot_20231214_132655](https://github.com/Friendly0Fire/GW2Radial/assets/2807024/e57bba32-26b5-491a-ad5e-4d6899444053)

Unfortunately all three result in the same crash.

**Comment by Friendly0Fire** [comment]
Check https://github.com/Friendly0Fire/GW2Radial/discussions/281 for tips and to follow up on the discussion. I will be closing this since, as I have already said, I do not have the bandwidth/ability to support Linux.
