### ISSUE TITLE
Radial menus for profession skills, weapon skills and utility skills

### ISSUE THREAD

**Issue by Monkeybtm6** [Friendly0Fire/GW2Radial#69]
I am a disabled gamer and can have trouble reaching some keyboard keys quickly, and if it would be possible to make more radial menus like that for other keybinds so my hand doesnt need to move all over the keyboard and not need to turn off action camera and move the mouse all the way down to click skills.

**Comment by Friendly0Fire** [comment]
Promoting this to a full feature for 1.2. The system will essentially allow you to configure your own radial menus (with either text or icons) and bind your desired keys to them, in addition to the default ones provided.

**Comment by jiangyi0923** [comment]
yes.you are right ,i just copy mount.h and.cpp to make it,and add a small imgui window to flow mouse post .it  must be safe.

**Comment by jiangyi0923** [comment]
https://github.com/jiangyi0923/GW2Addons/tree/oldc   this is old version ,
It seems to me that using imgui's imgui ::BeginTabBar() method is more convenient than the method you're using now,You can see how it works in SettingsMenu.cpp.
https://github.com/jiangyi0923/GW2Addons/tree/chinese this is 1.22 version ,
When I added ImGuiWindowFlags_AlwaysAutoResize to the window using your new method, there was a problem with the window. It would only show tabs

**Comment by Friendly0Fire** [comment]
As much as I appreciate doing things right sometimes, the current setup is working just fine and I'd rather spend what little time I have on more important features.

Also, please try to open a new issue rather than reusing this issue which is for a completely different feature.

**Comment by xvwyh** [comment]
@jiangyi0923, hi, I created that tabbed settings menu. I am aware that ImGui implemented tabbed panels now, but GW2Radial uses an older version of ImGui that didn't yet support them, so I chose to work with what I have and "fake" tabs with buttons, instead of forcing the author to update ImGui, which could possibly:
- cause a headache to update the code if ImGui made some breaking changes
- make it incompatible with arcdps, which also uses an old ImGui version
- create additional complications on the path of making it compatible with d912pxy
