### ISSUE TITLE
Emote Wheel

### ISSUE THREAD

**Issue by dewabuanam** [Friendly0Fire/GW2Radial#85]
add about 8 or 10 emote wheel that can customizeable (in wheele have max 10 but we can change the selected wheel) because we have so much emote, if include it all it will not good to look at (perharps).

**Comment by Friendly0Fire** [comment]
Emotes don't use keybinds and would require manipulating chat, so it is highly unlikely that I will implement this.

**Comment by dewabuanam** [comment]
Is that illegal to manipulating chat?

**Comment by Friendly0Fire** [comment]
It's iffy. It breaks the rule of "1 input = 1 output", since you need to type in multiple characters, but that's not really the main issue, which is that since I don't know the state of the chat window, I'd have to just send the emote to chat and hope for the best, which would cause all sorts of issues if the chat window is not open or is closed midway. If I also open the chat window automatically beforehand, then I risk other problems, like closing it when it was already open.

I just don't really see a way to make it work well and within ANet's guidelines.

**Comment by dewabuanam** [comment]
If chat command key setting "/" and you hit it. It doesn't care state chat window open or close it still open chat window with type "/" in it. And ofc if when chat window open it wouldn't open the wheel.
